import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

/**
 * A typed view of the tables the family workflow added.
 *
 * `src/integrations/supabase/types.ts` is GENERATED by `supabase gen types`
 * against a live project, and it has not been regenerated since the family-case
 * migrations landed — it still contains no `family_cases`, no
 * `family_case_events`, and none of the response metadata columns.
 *
 * The alternative that was tried and reverted was `supabase as any` at each call
 * site. That compiles, but it switches off checking for the WHOLE client at that
 * point: a typo in a column name, a filter on a field that does not exist, a
 * misspelled table — all of it passes review and fails at runtime, in an export
 * an administrator is running at the end of a study. Declaring the gap once, as
 * a real schema, keeps every call site checked and confines the compromise to
 * this file.
 *
 * WHEN types.ts IS REGENERATED: run
 *   supabase gen types typescript --project-id <ref> > src/integrations/supabase/types.ts
 * then repoint these imports at the plain `supabase` client and delete this
 * module. The shapes below are deliberately identical to what the generator
 * emits, so that change is mechanical. If it is NOT mechanical, the generated
 * schema and the migration disagree — investigate that rather than casting.
 */

export type FamilyCaseStatusValue =
  | "not_started"
  | "opened"
  | "in_progress"
  | "completed"
  | "expired"
  | "reopened";

/**
 * These are `type` aliases and not `interface`s on purpose. postgrest-js
 * constrains every table's Row to `Record<string, unknown>`; an interface has no
 * implicit index signature and silently fails that constraint, which collapses
 * the whole schema to `never` and makes every insert a type error with an
 * unreadable message. A type alias satisfies it.
 */
type FamilyCaseRecord = {
  id: string;
  reference_id: string;
  deceased_name: string;
  family_head_name: string;
  relationship: string;
  phone: string;
  district: string;
  village: string | null;
  preferred_language: "en" | "te";
  notes: string | null;
  survey_id: string;
  status: FamilyCaseStatusValue;
  access_token: string;
  pin: string;
  pin_issued_at: string;
  failed_attempts: number;
  locked_until: string | null;
  expires_at: string;
  opened_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  draft: unknown;
  draft_updated_at: string | null;
  response_id: string | null;
  officer_id: string | null;
  officer_name: string | null;
  created_at: string;
  updated_at: string;
};

type FamilyCaseEventRecord = {
  id: string;
  case_id: string;
  event: string;
  detail: unknown;
  actor: string;
  created_at: string;
};

/**
 * Only the columns this feature reads. `completion_pct` is GENERATED ALWAYS in
 * the database (see 20260721094500_response_answer_metadata.sql), so it is
 * readable but must never appear in an Insert or Update — omitting it from those
 * two shapes turns a runtime Postgres error into a compile error.
 */
type SurveyResponseRecord = {
  id: string;
  survey_id: string;
  family_case_id: string | null;
  reference_id: string | null;
  language: string;
  submitted_at: string;
  started_at: string | null;
  duration_seconds: number | null;
  question_count: number | null;
  answered_count: number | null;
  completion_pct: number | null;
};

type SurveyRecord = {
  id: string;
  title_en: string;
  title_te: string | null;
  description_en: string | null;
  description_te: string | null;
  status: string;
  slug: string | null;
};

/** Every column optional — the database supplies a default for each that matters. */
type Insertable<T> = { [K in keyof T]?: T[K] };

export type FamilyDatabase = {
  /**
   * The generator emits this so `createClient<Database>` resolves its overloads
   * without a second type argument. Its absence is what makes every `.insert()`
   * here collapse to `never`.
   */
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      family_cases: {
        Row: FamilyCaseRecord;
        Insert: Insertable<FamilyCaseRecord>;
        Update: Insertable<FamilyCaseRecord>;
        Relationships: [];
      };
      family_case_events: {
        Row: FamilyCaseEventRecord;
        Insert: Insertable<FamilyCaseEventRecord>;
        Update: Insertable<FamilyCaseEventRecord>;
        Relationships: [];
      };
      survey_responses: {
        Row: SurveyResponseRecord;
        Insert: Insertable<Omit<SurveyResponseRecord, "completion_pct">>;
        Update: Insertable<Omit<SurveyResponseRecord, "completion_pct">>;
        Relationships: [];
      };
      surveys: {
        Row: SurveyRecord;
        Insert: Insertable<SurveyRecord>;
        Update: Insertable<SurveyRecord>;
        Relationships: [];
      };
    };
    /**
     * `{ [_ in never]: never }`, not `Record<string, never>`. `.from()` resolves
     * a relation against Tables AND Views, so an index signature claiming every
     * string key is `never` makes every table lookup collapse to `never`.
     */
    Views: { [_ in never]: never };
    Functions: {
      expire_stale_family_cases: {
        Args: Record<string, never>;
        Returns: number;
      };
      family_case_stats: {
        Args: Record<string, never>;
        Returns: {
          total: number;
          not_started: number;
          opened: number;
          in_progress: number;
          completed: number;
          expired: number;
          completed_today: number;
          avg_completion_seconds: number | null;
        }[];
      };
    };
    Enums: {
      family_case_status: FamilyCaseStatusValue;
    };
    CompositeTypes: { [_ in never]: never };
  };
};

/**
 * The same singleton client, re-typed. Identical connection, identical auth
 * session — only the compile-time schema differs, which is why this is a cast
 * and not a second client. A second `createClient` would give the app two
 * independent auth listeners and a race on token refresh.
 */
export const familyDb = supabase as unknown as SupabaseClient<FamilyDatabase, "public">;
