// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// The URL and the *publishable* key are public by design — they ship in the
// browser bundle no matter what, and access is governed by row-level security,
// not by hiding them. So they are safe, and necessary, as fallback defaults:
// without them a host that has not set the VITE_* env vars (e.g. a fresh Vercel
// project) crashes on boot with "supabaseUrl is required" and renders a blank
// page. Env vars still take precedence, so staging/other projects can override.
// A secret/service-role key must NEVER appear here — the guard below enforces it.
const FALLBACK_SUPABASE_URL = "https://rmqyyyhkpcspnksarofv.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_eW_zqhU5HBMKOSK4b38wUQ_Q5Zzl1sk";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

function requirePublicSupabaseConfig() {
  if (SUPABASE_PUBLISHABLE_KEY.startsWith("sb_secret_") || SUPABASE_PUBLISHABLE_KEY.includes("service_role")) {
    throw new Error("Refusing to initialize Supabase with a secret/service role key in the browser.");
  }

  return { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY };
}

function isNewSupabasePublishableKey(value: string): boolean {
  return value.startsWith("sb_publishable_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabasePublishableKey(supabaseKey) && headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const config = requirePublicSupabaseConfig();

export const supabase = createClient<Database>(config.url, config.key, {
  global: {
    fetch: createSupabaseFetch(config.key),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});